### PR TITLE
Sped up encode62 and decode62

### PR DESCRIPTION
**Pull request by sfcgeorge**
I have refactored the code to speed up the encode62 and decode62 methods. My benchmarks show encode62 is 20% faster and decode62 is 100% faster. Their functionality stays the same so all the tests still pass. I have also added a few tests where relevant. I will explain the changes:
### Encode62
- Changed the order of the if statement so that the most common choice comes fast and the least common last. This means less time is spent performing comparisons in most cases.
- Switched `.modulo()` method to `%` modulo operator as this is faster. Not sure why, perhaps an extra method call.
### Decode62
- Added `ALPHABET_HASH` constant so that we can look up the number of each letter by key rather than using `.find_index()` which is slower.
- Changed the algorithm so that we aren't calculating a power within the loop, we can use `.each` rather than `.each_with_index` and removed the `.reverse` as the results come in the right order now already.
- Removed the Regex as this was slow. The same error checking is achieved by using `.find()` on the hash which raised an exception if the key is not found. We then catch that exception to return our own more descriptive exception from before.

This is a very minor pull request for a not huge speed increase, but I think it is still worth it, because a few milliseconds here and there could speed up a URL shortener. I love the gem, it's nice and simple. Thanks!

### CODE REVIEW

**Comment by sfcgeorge** [comment]
Oh, looks like this fails on 1.8.7, I'll look into it.

**Comment by sfcgeorge** [comment]
Yes! Fixed. For some reason in ruby 1.8.7 `.fetch()` would raise an IndexError whereas in 1.9.x onwards it raises a KeyError. So I have simply defined KeyError if it doesn't already exist. So Travis build passes, now all Rubies can get these speed improvements; ready to merge hopefully :)

**Comment by matiaskorhonen** [comment]
Merged and thanks!

**Comment by sfcgeorge** [comment]
Thank you! Any chance of a new gem release? As there are no new features just improvements you could make it `1.0.1`. Unless you count `ALPHABET_HASH` in which case you could make it `1.1.0`.

**Comment by matiaskorhonen** [comment]
I just pushed 1.0.1 to RubyGems

**Comment by sfcgeorge** [comment]
Fabulous, thanks!

**Pull request merged**
